# Generated by Django 4.0.1 on 2023-03-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_comment_level_comment_lft_comment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
    ]
